title: Gaëtan Jestin - CV
description: Personal CV
url: "https://cv.gaetan.cool"
baseurl: ""

permalink: /:slug.html

favicon: "icon.png"

markdown: kramdown

sass:
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
